### ISSUE TITLE
Windows not booting on Xiaomi Pad 5

### ISSUE THREAD

**Issue by rodriguezst** [Project-Aloha/DualBootKernelPatcher#1]
I have Windows 11 (secure boot disabled), Linux and HyperOS installed on a Xiaomi Pad 5. When booting an image generated with DBPK Linux boots fine but Windows does not. It tries to boot for a couple of seconds and then reboots. Windows boots fine with the uefi image generated at wow-msmnile repo (same uefi.fd).
I am passing mkbootimg the same headers as the Android boot image (HyperOS) but don’t know what else to try. Any hint?

You can see here how I am generating the images:
https://github.com/rodriguezst/nabu-dualboot-img/blob/7c42761f11083b49218cbee7b76ad0fc86e64b6d/.github/workflows/patch-boot.yml#L92

**Comment by sunflower2333** [comment]
@rodriguezst Does uefi load(like showing uefi logo) when condition match? ui

**Comment by sunflower2333** [comment]
@rodriguezst Maybe you should try reserve kernel region in memory map and recompile a uefi ...

**Comment by sunflower2333** [comment]
Please use Magiskboot to unpack/repack the boot image and do not edit the kernel header just keep it as it is. 

Also, if you boot android  please use full compact dtbs file instead of using overlayed dtb. You can get full dtb by unpacking original android's boot image.
